### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by AlphaLawless** [AlphaLawless/vindi-nodejs-unofficial#1]
Checklist das informações

- [ ] Criar README.md
- [x] Transferir pacote para o NPM

[Rotas](https://vindi.github.io/api-docs/dist/)

<details>
<summary>1. Customers</summary>

- [x] POST `/v1/customers`
- [x] GET `/v1/customers`
- [x] PUT `/v1/customers/{id}`
- [x] DELETE `/v1/customers/{id}`
- [x] GET `/v1/customers/{id}`
- [x] POST `/v1/customers/{id}/unarchive`

</details>

<details>
<summary>2. Plans</summary>

- [x] POST `/v1/plans`
- [x] GET `/v1/plans`
- [x] PUT `/v1/plans/{id}`
- [x] GET `/v1/plans/{id}`
- [x] GET `/v1/plans/{id}/plan_items`

</details>

<details>
<summary>3. Products</summary>

- [x] POST `/v1/products`
- [x] GET `/v1/plans`
- [x] PUT `/v1/plans/{id}`
- [x] GET `/v1/plans/{id}`
- [x] GET `/v1/plans/{id}/plan_items`

</details>

<details>
<summary>4. Payment Methods</summary>

- [x] GET `/v1/payment_methods`
- [x] GET `/v1/payment_methods/{id}`

</details>

<details>
<summary>5. Discounts</summary>

- [x] POST `/v1/discounts`
- [x] DELETE `/v1/discounts/{id}`
- [x] GET `/v1/discounts/{id}`

</details>

<details>
<summary>6. Subscriptions</summary>

- [x] POST `/v1/subscriptions`
- [x] GET `/v1/subscriptions`
- [x] DELETE `/v1/subscriptions/{id}`
- [x] PUT `/v1/subscriptions/{id}`
- [x] GET `/v1/subscriptions/{id}`
- [x] GET `/v1/subscriptions/{id}/product_items`
- [x] POST `/v1/subscriptions/{id}/reactivate`
- [x] POST `/v1/subscriptions/{id}/renew`

</details>

<details>
<summary>7. Product Items</summary>

- [x] POST `/v1/product_items`
- [x] DELETE `/v1/product_items/{id}`
- [ ] PUT `/v1/product_items/{id}`
- [x] GET `/v1/product_items/{id}`

</details>

<details>
<summary>8. Periods</summary>

- [x] GET `/v1/periods`
- [x] PUT `/v1/periods/{id}`
- [x] GET `/v1/periods/{id}`
- [x] POST `/v1/periods/{id}/bill`
- [x] GET `/v1/periods/{id}/usages`

</details>

<details>
<summary>9. Bills</summary>

- [ ] POST `/v1/bills`
- [x] GET `/v1/bills`
- [x] DELETE `/v1/bills/{id}`
- [x] PUT `/v1/bills/{id}`
- [x] GET `/v1/bills/{id}`
- [ ] POST `/v1/bills/{id}/approve`
- [ ] GET `/v1/bills/{id}/bill_items`
- [ ] POST `/v1/bills/{id}/charge`
- [ ] POST `/v1/bills/{id}/invoice`

</details>
<details>
<summary>10. Bill Items</summary>

- [x] GET `/v1/bill_items/{id}`
</details>

<details>
<summary>11. Charges</summary>

- [x] GET `/v1/charges`
- [x] DELETE `/v1/charges/{id}`
- [x] PUT `/v1/charges/{id}`
- [x] GET `/v1/charges/{id}`
- [x] POST `/v1/charges/{id}/capture`
- [x] POST `/v1/charges/{id}/charge`
- [x] POST `/v1/charges/{id}/fraud_review`
- [x] POST `/v1/charges/{id}/refund`
- [x] POST `/v1/charges/{id}/reissue`
</details>

<details>
<summary>12. Transactions</summary>

- [ ] POST `/v1/transactions`
- [x] GET `/v1/transactions`
- [x] PUT `/v1/transactions/{id}`
- [x] GET `/v1/transactions/{id}`
- [ ] GET `/v1/transactions/recoveries`
</details>

<details>
<summary>13. Payment Profiles</summary>

- [x] POST `/v1/payment_profiles`
- [x] GET `/v1/payment_profiles`
- [ ] PUT `/v1/payment_profiles/{id}`
- [x] DELETE `/v1/payment_profiles/{id}`
- [ ] GET `/v1/payment_profiles/recoveries`
- [ ] POST `/v1/payment_profiles/{id}/verify`
</details>

<details>
<summary>14. Usages</summary>

- [ ] POST `/v1/usages`
- [ ] DELETE `/v1/usages/{id}`
</details>

<details>
<summary>15. Invoices</summary>

- [ ] POST `/v1/invoices`
- [ ] GET `/v1/invoices`
- [ ] DELETE `/v1/invoices/{id}`
- [ ] PUT `/v1/invoices/{id}`
- [ ] GET `/v1/invoices/{id}`
- [ ] POST `/v1/invoices/{id}/retry`
</details>

<details>
<summary>16. Movements</summary>

- [x] POST `/v1/movements`
- [x] DELETE`/v1/movements/{id}`
</details>

<details>
<summary>17. Messages</summary>

- [x] POST `/v1/messages`
- [x] GET `/v1/movements`
- [x] GET `/v1/movements/{id}`
</details>

<details>
<summary>18. Export Batches</summary>

- [ ] GET `/v1/export_batches`
- [ ] POST `/v1/export_batches`
- [ ] GET `/v1/export_batches/{id}`
- [ ] POST `/v1/export_batches/{id}/approve`
</details>

<details>
<summary>19. Import Batches</summary>

- [ ] POST `/v1/import_batches`
- [ ] GET `/v1/import_batches`
- [ ] GET `/v1/import_batches/{id}`
</details>

<details>
<summary>20. Issues</summary>

- [x] GET `/v1/issues`
- [x] PUT `/v1/issues/{id}`
- [x] GET `/v1/issues/{id}`
</details>

<details>
<summary>21. Notifications</summary>

- [ ] POST `/v1/notifications`
- [ ] GET `/v1/notifications`
- [ ] DELETE `/v1/notifications/{id}`
- [ ] PUT `/v1/notifications/{id}`
- [ ] GET `/v1/notifications/{id}`
- [ ] POST `/v1/notifications/{id}/notification_items`
- [ ] GET `/v1/notifications/{id}/notification_items`
- [ ] DELETE `/v1/notifications/{id}/notification_items`
</details>

<details>
<summary>22. Merchants</summary>

- [x] GET `/v1/merchants`
- [ ] PATCH `/v1/merchants/{id}`
- [ ] GET `/v1/merchants/{id}`
- [ ] GET `/v1/merchants/current`
</details>

<details>
<summary>23. Merchant Users</summary>

- [ ] POST `/v1/merchant_users`
- [ ] GET `/v1/merchant_users`
- [ ] DELETE `/v1/merchant_users/{id}`
- [ ] PUT `/v1/merchant_users/{id}`
- [ ] GET `/v1/merchant_users/{id}`
- [ ] POST `/v1/merchant_users/{id}/reactivate`
</details>

<details>
<summary>24. Roles</summary>

- [x] GET `/v1/roles`
</details>

<details>
<summary>25. Users</summary>

- [x] GET `/v1/users/current`
</details>

<details>
<summary>26. Public</summary>

- [x] POST `/v1/public/payment_profiles`
</details>

<details>
<summary>27. Affiliates</summary>

- [ ] GET `/v1/affiliates`
- [ ] POST `/v1/affiliates`
- [ ] PUT `/v1/affiliates/{id}`
- [ ] GET `/v1/affiliates/{id}`
- [ ] PUT `/v1/affiliates/{id}/verify`
</details>

<details>
<summary>28. Partner</summary>

- [ ] POST `/v1/partner/accounts`
- [ ] GET `/v1/partner/accounts`
</details>
